### ISSUE TITLE
Update Fastpath Webchat for Smack 4.1.8

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/Fastpath-webchat#13]
...Migrated from [Ignite Jira OF-1190](https://issues.igniterealtime.org/projects/OF/issues/OF-1190)...

HeroPD (https://community.igniterealtime.org/people/munkhuu) has provided PR updating Fastpath Webchat to current Smack. https://github.com/igniterealtime/Fastpath-webchat/pull/10

If commited and working fine (he has to provide feedback if it is working after this changes) Webchat plugin can probably be re-introduced to the plugins download page.

**Comment by guusdk** [comment]
We've upgraded to a recent version of Smack by merging #11
