### ISSUE TITLE
Help with compile to war

### ISSUE THREAD

**Issue by albertusgeyser** [igniterealtime/Fastpath-webchat#24]
Good Day

Could anyone help to explain how to compile to war file to upload to openfire?
Or maybe have a war file i can use?

Thank You

Albertus Geyser

**Comment by wrooot** [comment]
Bug tracker is meant to file actual bugs or feature requests. General inquires should be posted in the forums. I saw you already did. Don't expect to get an answer so quickly. Especially for Webchat, which is obsolete and not currently supported. There are only a few volunteers here. It might be that nobody will answer.

**Comment by albertusgeyser** [comment]
Sorry for posting here.
@wrooot you do not have anything to help?

**Comment by wrooot** [comment]
No. As i've explained, there are only 3-4 volunteers here working on projects, but everyone has they day jobs and other stuff to do. Fastpath is an old and not maintained thing, especially Webchat part. This is a legacy bit left from times when Jive Software was developing it. Nobody has expertize in it, nor time to support it. I am not a developer myself.
