### ISSUE TITLE
active development?

### ISSUE THREAD

**Issue by derrickaubin** [igniterealtime/Fastpath-webchat#9]
Hi,

Can't find a forum to ask this question, so I figured I'd ask it here.  I'm wondering why OpenFire says this is a discontinued plugin, when there is obvious activity going on here?

Looking forward to experimenting with this.  Is it production grade?

Thanks,
Derrick

**Comment by akrherz** [comment]
The forums are here:

https://community.igniterealtime.org/community/discontinued-projects/fastpath
